name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    # Spin up a temporary MongoDB database just for the tests!
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install Dependencies
        run: cd backend && npm install

      - name: Run Tests
        run: cd backend && npm test

  deploy:
    name: Deploy to EC2
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/idea-vault
            git pull origin main
            
            # Build Frontend
            cd frontend
            npm install
            npm run build
            
            # Restart Backend
            cd ../backend
            npm install
            pm2 restart ideavault
